### ISSUE TITLE
Duplicated WHEELS_SEPARATION

### ISSUE THREAD

**Issue by cua-cua** [Bulebots/bulebule#402]
Which macro is the Ok one? Choose one and remove the other one.

- config.h -> WHEELS_SEPARATION = 0.0785 (default of the static variable wheels_separation on the file encoder.c. used on the function update_encoder_readings, it can be changed with command)
- setup.h -> MOUSE_WHEELS_SEPARATION = 0.065 (used on the function inplace_turn from speed.c)

**Comment by Peque** [comment]
They are different. I think:

- WHEELS_SEPARATION: it is a calibratable. It could be used to get the angular speed from the encoders instead of the gyro. We do not really use that functionality right now, but it may be useful to leave it there (?).
- MOUSE_WHEELS_SEPARATION: it is a robot's physics constant. Not really calibratable. It is used to calculate the forces on the tires while turning.
