### ISSUE TITLE
Help at Loading the code to the bluepill

### ISSUE THREAD

**Issue by fatihbayir** [Bulebots/bulebule#434]
Hi all,

I am very unfamiliar with the concepts such as docker, linux, gnu, make, makefile etc.. I am sorry but all those are non sense to me. I am using windows 8. how can I uplaod this micromouse code to the blue pill? Or In order to learn github terminology where should I start at? Pls refer me to a good source to understand the operations of github so that I can load the code. Thanks in advance.

**Comment by Peque** [comment]
I think we are unable to help you with such a broad issue.

My recommendation is for you to take it easy and assume it will take you some time to learn all the stuff you need before working with this project. There are plenty of video tutorials, which I think are a great starting point for a beginner, about GitHub, Docker, Linux, GNU, and everything else.

You will need to watch hours of videos and play around and learn during days or weeks, but it will be worth it.

Good luck! :blush: 

PS: my recommendation if you are going to work with Bulebule is to start by installing a GNU/Linux distribution and use it instead of Windows. I could recommend Fedora, since that is what we use, but any other distribution (like Ubuntu) will do.
